*** This file was created by VarLabels.do
*** on 10 Jun 2022 at 12:54:48. 
*** 
********************************************** 


capture label variable v_sold_7e13 "value sold last 12 mt: Fresh Maize"
capture label variable q_sold_7e13 "quant sold last 12 mt: Fresh Maize"
capture label variable q_cons_7e13 "quant own cons annualized: Fresh Maize"
capture label variable v_sold_7e14 "value sold last 12 mt: Cassava cooking"
capture label variable q_sold_7e14 "quant sold last 12 mt: Cassava cooking"
capture label variable q_cons_7e14 "quant own cons annualized: Cassava cooking"
capture label variable v_sold_7e15 "value sold last 12 mt: Cassava for flour"
capture label variable q_sold_7e15 "quant sold last 12 mt: Cassava for flour"
capture label variable q_cons_7e15 "quant own cons annualized: Cassava for flour"
capture label variable v_sold_7e16 "value sold last 12 mt: Colocasia"
capture label variable q_sold_7e16 "quant sold last 12 mt: Colocasia"
capture label variable q_cons_7e16 "quant own cons annualized: Colocasia"
capture label variable v_sold_7e17 "value sold last 12 mt: Sweet"
capture label variable q_sold_7e17 "quant sold last 12 mt: Sweet"
capture label variable q_cons_7e17 "quant own cons annualized: Sweet"
capture label variable v_sold_7e18 "value sold last 12 mt: Yam Amateke"
capture label variable q_sold_7e18 "quant sold last 12 mt: Yam Amateke"
capture label variable q_cons_7e18 "quant own cons annualized: Yam Amateke"
capture label variable v_sold_7e19 "value sold last 12 mt: Banana fruits"
capture label variable q_sold_7e19 "quant sold last 12 mt: Banana fruits"
capture label variable q_cons_7e19 "quant own cons annualized: Banana fruits"
capture label variable v_sold_7e20 "value sold last 12 mt: Banana cooking"
capture label variable q_sold_7e20 "quant sold last 12 mt: Banana cooking"
capture label variable q_cons_7e20 "quant own cons annualized: Banana cooking"
capture label variable v_sold_7e21 "value sold last 12 mt: Banana Beer"
capture label variable q_sold_7e21 "quant sold last 12 mt: Banana Beer"
capture label variable q_cons_7e21 "quant own cons annualized: Banana Beer"
capture label variable v_sold_7e22 "value sold last 12 mt: Mangoes"
capture label variable q_sold_7e22 "quant sold last 12 mt: Mangoes"
capture label variable q_cons_7e22 "quant own cons annualized: Mangoes"
capture label variable v_sold_7e23 "value sold last 12 mt: Papayas or pawpaw"
capture label variable q_sold_7e23 "quant sold last 12 mt: Papayas or pawpaw"
capture label variable q_cons_7e23 "quant own cons annualized: Papayas or pawpaw"
capture label variable v_sold_7e24 "value sold last 12 mt: Avocado"
capture label variable q_sold_7e24 "quant sold last 12 mt: Avocado"
capture label variable q_cons_7e24 "quant own cons annualized: Avocado"
capture label variable v_sold_7e25 "value sold last 12 mt: Pineapples"
capture label variable q_sold_7e25 "quant sold last 12 mt: Pineapples"
capture label variable q_cons_7e25 "quant own cons annualized: Pineapples"
capture label variable v_sold_7e26 "value sold last 12 mt: Guave"
capture label variable q_sold_7e26 "quant sold last 12 mt: Guave"
capture label variable q_cons_7e26 "quant own cons annualized: Guave"
capture label variable v_sold_7e27 "value sold last 12 mt: Orange"
capture label variable q_sold_7e27 "quant sold last 12 mt: Orange"
capture label variable q_cons_7e27 "quant own cons annualized: Orange"
capture label variable v_sold_7e28 "value sold last 12 mt: Mandarins"
capture label variable q_sold_7e28 "quant sold last 12 mt: Mandarins"
capture label variable q_cons_7e28 "quant own cons annualized: Mandarins"
capture label variable v_sold_7e29 "value sold last 12 mt: Lemon or citron"
capture label variable q_sold_7e29 "quant sold last 12 mt: Lemon or citron"
capture label variable q_cons_7e29 "quant own cons annualized: Lemon or citron"
capture label variable v_sold_7e30 "value sold last 12 mt: Pamplemousse"
capture label variable q_sold_7e30 "quant sold last 12 mt: Pamplemousse"
capture label variable q_cons_7e30 "quant own cons annualized: Pamplemousse"
capture label variable v_sold_7e31 "value sold last 12 mt: Lime or Maracouja"
capture label variable q_sold_7e31 "quant sold last 12 mt: Lime or Maracouja"
capture label variable q_cons_7e31 "quant own cons annualized: Lime or Maracouja"
capture label variable v_sold_7e32 "value sold last 12 mt: Plums"
capture label variable q_sold_7e32 "quant sold last 12 mt: Plums"
capture label variable q_cons_7e32 "quant own cons annualized: Plums"
capture label variable v_sold_7e33 "value sold last 12 mt: Strawberriers"
capture label variable q_sold_7e33 "quant sold last 12 mt: Strawberriers"
capture label variable q_cons_7e33 "quant own cons annualized: Strawberriers"
capture label variable v_sold_7e34 "value sold last 12 mt: Coeur de boeuf"
capture label variable q_sold_7e34 "quant sold last 12 mt: Coeur de boeuf"
capture label variable q_cons_7e34 "quant own cons annualized: Coeur de boeuf"
capture label variable v_sold_7e35 "value sold last 12 mt: Others fruits Ibifenesi"
capture label variable q_sold_7e35 "quant sold last 12 mt: Others fruits Ibifenesi"
capture label variable q_cons_7e35 "quant own cons annualized: Others fruits Ibifenesi"
capture label variable v_sold_7e36 "value sold last 12 mt: Other fruits"
capture label variable q_sold_7e36 "quant sold last 12 mt: Other fruits"
capture label variable q_cons_7e36 "quant own cons annualized: Other fruits"
capture label variable v_sold_7e37 "value sold last 12 mt: Fresh Beans"
capture label variable q_sold_7e37 "quant sold last 12 mt: Fresh Beans"
capture label variable q_cons_7e37 "quant own cons annualized: Fresh Beans"
capture label variable v_sold_7e38 "value sold last 12 mt: Green Beans"
capture label variable q_sold_7e38 "quant sold last 12 mt: Green Beans"
capture label variable q_cons_7e38 "quant own cons annualized: Green Beans"
capture label variable v_sold_7e39 "value sold last 12 mt: Tomato"
capture label variable q_sold_7e39 "quant sold last 12 mt: Tomato"
capture label variable q_cons_7e39 "quant own cons annualized: Tomato"
capture label variable v_sold_7e40 "value sold last 12 mt: Onions"
capture label variable q_sold_7e40 "quant sold last 12 mt: Onions"
capture label variable q_cons_7e40 "quant own cons annualized: Onions"
capture label variable v_sold_7e41 "value sold last 12 mt: Garlic"
capture label variable q_sold_7e41 "quant sold last 12 mt: Garlic"
capture label variable q_cons_7e41 "quant own cons annualized: Garlic"
capture label variable v_sold_7e42 "value sold last 12 mt: Pepper"
capture label variable q_sold_7e42 "quant sold last 12 mt: Pepper"
capture label variable q_cons_7e42 "quant own cons annualized: Pepper"
capture label variable v_sold_7e43 "value sold last 12 mt: Sweet Pepper"
capture label variable q_sold_7e43 "quant sold last 12 mt: Sweet Pepper"
capture label variable q_cons_7e43 "quant own cons annualized: Sweet Pepper"
capture label variable v_sold_7e44 "value sold last 12 mt: Squash or Vegetable marrows"
capture label variable q_sold_7e44 "quant sold last 12 mt: Squash or Vegetable marrows"
capture label variable q_cons_7e44 "quant own cons annualized: Squash or Vegetable marrows"
capture label variable v_sold_7e45 "value sold last 12 mt: Zucchini or cucumber"
capture label variable q_sold_7e45 "quant sold last 12 mt: Zucchini or cucumber"
capture label variable q_cons_7e45 "quant own cons annualized: Zucchini or cucumber"
capture label variable v_sold_7e46 "value sold last 12 mt: Eggplant"
capture label variable q_sold_7e46 "quant sold last 12 mt: Eggplant"
capture label variable q_cons_7e46 "quant own cons annualized: Eggplant"
capture label variable v_sold_7e47 "value sold last 12 mt: Carotts"
capture label variable q_sold_7e47 "quant sold last 12 mt: Carotts"
capture label variable q_cons_7e47 "quant own cons annualized: Carotts"
capture label variable v_sold_7e48 "value sold last 12 mt: Leeks"
capture label variable q_sold_7e48 "quant sold last 12 mt: Leeks"
capture label variable q_cons_7e48 "quant own cons annualized: Leeks"
capture label variable v_sold_7e49 "value sold last 12 mt: Cabbages"
capture label variable q_sold_7e49 "quant sold last 12 mt: Cabbages"
capture label variable q_cons_7e49 "quant own cons annualized: Cabbages"
capture label variable v_sold_7e50 "value sold last 12 mt: Lettuce or Laitue"
capture label variable q_sold_7e50 "quant sold last 12 mt: Lettuce or Laitue"
capture label variable q_cons_7e50 "quant own cons annualized: Lettuce or Laitue"
capture label variable v_sold_7e51 "value sold last 12 mt: Parsley"
capture label variable q_sold_7e51 "quant sold last 12 mt: Parsley"
capture label variable q_cons_7e51 "quant own cons annualized: Parsley"
capture label variable v_sold_7e52 "value sold last 12 mt: Seleri"
capture label variable q_sold_7e52 "quant sold last 12 mt: Seleri"
capture label variable q_cons_7e52 "quant own cons annualized: Seleri"
capture label variable v_sold_7e53 "value sold last 12 mt: Mushroom or spinac"
capture label variable q_sold_7e53 "quant sold last 12 mt: Mushroom or spinac"
capture label variable q_cons_7e53 "quant own cons annualized: Mushroom or spinac"
capture label variable v_sold_7e54 "value sold last 12 mt: Ibishayote"
capture label variable q_sold_7e54 "quant sold last 12 mt: Ibishayote"
capture label variable q_cons_7e54 "quant own cons annualized: Ibishayote"
capture label variable v_sold_7e55 "value sold last 12 mt: Fresh small weight"
capture label variable q_sold_7e55 "quant sold last 12 mt: Fresh small weight"
capture label variable q_cons_7e55 "quant own cons annualized: Fresh small weight"
capture label variable v_sold_7e56 "value sold last 12 mt: Mushrooms"
capture label variable q_sold_7e56 "quant sold last 12 mt: Mushrooms"
capture label variable q_cons_7e56 "quant own cons annualized: Mushrooms"
capture label variable v_sold_7e57 "value sold last 12 mt: Cassava leaves"
capture label variable q_sold_7e57 "quant sold last 12 mt: Cassava leaves"
capture label variable q_cons_7e57 "quant own cons annualized: Cassava leaves"
capture label variable v_sold_7e58 "value sold last 12 mt: Green vegetables Inyabutongo"
capture label variable q_sold_7e58 "quant sold last 12 mt: Green vegetables Inyabutongo"
capture label variable q_cons_7e58 "quant own cons annualized: Green vegetables Inyabutongo"
capture label variable v_sold_7e59 "value sold last 12 mt: Imbwija"
capture label variable q_sold_7e59 "quant sold last 12 mt: Imbwija"
capture label variable q_cons_7e59 "quant own cons annualized: Imbwija"
capture label variable v_sold_7e60 "value sold last 12 mt: Ibisusa"
capture label variable q_sold_7e60 "quant sold last 12 mt: Ibisusa"
capture label variable q_cons_7e60 "quant own cons annualized: Ibisusa"
capture label variable v_sold_7e61 "value sold last 12 mt: Umushogoro"
capture label variable q_sold_7e61 "quant sold last 12 mt: Umushogoro"
capture label variable q_cons_7e61 "quant own cons annualized: Umushogoro"
capture label variable v_sold_7e62 "value sold last 12 mt: Isogo"
capture label variable q_sold_7e62 "quant sold last 12 mt: Isogo"
capture label variable q_cons_7e62 "quant own cons annualized: Isogo"
capture label variable v_sold_7e63 "value sold last 12 mt: Other vegetables"
capture label variable q_sold_7e63 "quant sold last 12 mt: Other vegetables"
capture label variable q_cons_7e63 "quant own cons annualized: Other vegetables"
capture label variable v_sold_7e64 "value sold last 12 mt: Tea"
capture label variable q_sold_7e64 "quant sold last 12 mt: Tea"
capture label variable q_cons_7e64 "quant own cons annualized: Tea"
capture label variable v_sold_7e65 "value sold last 12 mt: Cane sugar"
capture label variable q_sold_7e65 "quant sold last 12 mt: Cane sugar"
capture label variable q_cons_7e65 "quant own cons annualized: Cane sugar"
capture label variable v_sold_7e66 "value sold last 12 mt: Pyretre Ibireti"
capture label variable q_sold_7e66 "quant sold last 12 mt: Pyretre Ibireti"
capture label variable q_cons_7e66 "quant own cons annualized: Pyretre Ibireti"
capture label variable v_sold_7e68 "value sold last 12 mt: Macadamiya"
capture label variable q_sold_7e68 "quant sold last 12 mt: Macadamiya"
capture label variable q_cons_7e68 "quant own cons annualized: Macadamiya"
capture label variable v_sold_7e69 "value sold last 12 mt: Muringa"
capture label variable q_sold_7e69 "quant sold last 12 mt: Muringa"
capture label variable q_cons_7e69 "quant own cons annualized: Muringa"
capture label variable v_sold_7e70 "value sold last 12 mt: Others"
capture label variable q_sold_7e70 "quant sold last 12 mt: Others"
capture label variable q_cons_7e70 "quant own cons annualized: Others"
